name: kainato_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home/

scripts:
  build_web: flutter build web # Cria o aplicativo na versão web
  docs: mkdir docs # Cria o diretório onde será armazenado o código fonte web do projeto
  copy: xcopy /E /H /Y build\web\* docs\ # Copia todo o conteúdo para a pasta de documentos.
